#!/bin/sh
if [ $# != 5 ]; then
  echo "Usages:"
  echo "======"
  echo "$0 ND_COLLECTOR_PORT TierName ServerName AppName Test_run_number"
  echo "Example"
  echo "$0 7802 T1 S1 A1 12227"
  exit -1
fi

i=1
#while [ $i -le 5000 ]
while [ $i -le 1 ]
do
#echo 
ndi_send_msg_ex 127.0.0.1 $1 "nd_meta_data_req:action=get_thread_dump;Tier=$2;Server=$3;Instance=$4;CompressMode=1;TestNum=$5
"
echo "take thread dump"
#sleep 10
i=`expr $i + 1`
done
exit 0
