#----------------------------------------------------------------------------------------------------#  
#  Generated by needle                                                                               #
#  Convention: ALL variables starts with K followed by underscore and appropriate name               #
#  Note: Do not use blank line and spaces. Comments are allowed                                      #
#----------------------------------------------------------------------------------------------------#

$K_TNAME|$K_NUM_USERS|$K_RAMP_UP_TIME|$K_DURATION|$K_RAMP_DOWN_TIME|$K_SCRIPT1|$K_SCRIPT2|$K_SCRIPT3|$K_SCRIPT4|$K_SCRIPT5|$K_SCRIPT6|$K_ND_SVR|$K_SVR_HOST1|$K_SVR_HOST2|$K_SVR_HOST3|$K_SVR_HOST4|$K_SVR_HOST5|$K_SVR_HOST6|$K_RR_MODE|$K_REPORTING|$K_SESSION_PACING|$K_O_THINK_TIME|$K_THINK_TIME|$K_NEW_USER|$K_TRACING|$K_FEATURE

#ThreadDump & HeapDump 
SMOKE-017-001|3|ALL IMMEDIATELY|TIME 00:05:00|ALL IMMEDIATELY|nsecomnodejs_10|nsecomnodejs_14|kubensecomnodejs_10|kubensecomnodejs_12|kubensecomnodejs_14|kubehapinodejs_12|2 10.10.70.37:7898 NETJS-017-001|127.0.0.1 10.10.70.38:3000 -|127.0.0.1 10.10.30.5:3000 -|127.0.0.1 10.10.70.99:30010 -|127.0.0.1 10.10.70.99:30012 -|127.0.0.1 10.10.70.99:30014 -|127.0.0.1 10.10.70.99:30030 -|1|ALL 2|ALL 1 0 2000|ALL ALL 1|ALL ALL 3 5000 8000|ALL 1|ALL 0 0 0 0|#Feature:ThreadDump & HeapDump
