#!/usr/bin/env bash

host_5=10.10.30.5
user_5=root
passwd_5=automation5
user_Cav_5=cavisson
passwd_Cav_5=cavisson
                   
cmd_stop_nod_5="pkill -9 -f pm2"

sleep 5                 
echo "[RMON] Stop Agent 30.5"
rmon -h $host_5 -u $user_5 -p $passwd_5 -c "$cmd_stop_nod_5"

sleep 5
cmd_copy_nod_5="cp /root/scripts/webapp/nsecom/Original/ndsettings.conf /root/scripts/webapp/nsecom/ndsettings.conf"
   
sleep 5      
echo "[RMON] Ndsettings file copy 30.5"
rmon -h $host_5 -u $user_5 -p $passwd_5 -c "$cmd_copy_nod_5"
         
sleep 5
cmd_start_nod_5="pm2 start /root/scripts/webapp/nsecom/bin/www -i 1"
               
sleep 5                 
echo "[RMON] Start Agent 30.5"
rmon -h $host_5 -u $user_5 -p $passwd_5 -c "$cmd_start_nod_5"

exit 0
