#----------------------------------------------------------------------------------------------------#  
#  Generated by needle                                                                            #
#  Convention: ALL variables starts with K followed by underscore and appropriate name               #
#  Note: Do not use blank line and spaces. Comments are allowed                                      #
#----------------------------------------------------------------------------------------------------#

$K_TNAME|$K_NUM_USERS|$K_RAMP_UP_TIME|$K_DURATION|$K_RAMP_DOWN_TIME|$K_SCRIPT1|$K_ND_SVR|$K_SVR_HOST1|$K_RR_MODE|$K_REPORTING|$K_SESSION_PACING|$K_O_THINK_TIME|$K_THINK_TIME|$K_NEW_USER|$K_TRACING|$K_FEATURE

GOLANG-002-001|3|ALL IMMEDIATELY|TIME 00:01:30|ALL IMMEDIATELY|qorscript|2 10.10.30.5:7895 GOLANG-002-001|127.0.0.1 10.10.30.5:7000 -|1|ALL 1|ALL 1 0 2000|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|#Feature:HotSpot

GOLANG-002-002|3|ALL IMMEDIATELY|TIME 00:01:30|ALL IMMEDIATELY|qorscript|2 10.10.30.5:7895 GOLANG-002-001|127.0.0.1 10.10.30.5:7000 -|1|ALL 1|ALL 1 0 2000|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|#Feature:HotSpot

GOLANG-002-003|3|ALL IMMEDIATELY|TIME 00:01:30|ALL IMMEDIATELY|qorscript|2 10.10.30.5:7895 GOLANG-002-001|127.0.0.1 10.10.30.5:7000 -|1|ALL 1|ALL 1 0 2000|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|#Feature:HotSpot

GOLANG-002-004|3|ALL IMMEDIATELY|TIME 00:01:30|ALL IMMEDIATELY|qorscript|2 10.10.30.5:7895 GOLANG-002-001|127.0.0.1 10.10.30.5:7000 -|1|ALL 1|ALL 1 0 2000|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|#Feature:HotSpot

GOLANG-002-005|3|ALL IMMEDIATELY|TIME 00:01:30|ALL IMMEDIATELY|qorscript|2 10.10.30.5:7895 GOLANG-002-001|127.0.0.1 10.10.30.5:7000 -|1|ALL 1|ALL 1 0 2000|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|#Feature:HotSpot

GOLANG-002-006|3|ALL IMMEDIATELY|TIME 00:01:30|ALL IMMEDIATELY|qorscript|2 10.10.30.5:7895 GOLANG-002-001|127.0.0.1 10.10.30.5:7000 -|1|ALL 1|ALL 1 0 2000|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|#Feature:HotSpot
